sudo: required
language: bash

services:
  - docker

before_install:
  - docker pull debian:jessie

script:
  - curl -L https://raw.githubusercontent.com/bbashy/seedbox/master/install > install_seedbox
  - cat "answers" | sudo bash install_seedbox

notifications:
  email: false
